### PR TITLE
Transition to Scala

### PR DESCRIPTION
**Pull request by shkesar**
You can also accept the PR in a new branch.
The **README.md** file is also updated.

### CODE REVIEW

**Comment by shkesar** [comment]
Revert and make the decision to merge it with a new PR.

**Comment by AmanAgnihotri** [comment]
You revert all your changes. I'll send a PR to you for the changes that I have done. Fixes everything from addition of Java code again to the code formatting.

**Comment by shkesar** [comment]
I’m doing formatting changes in a new branch. As I said.

**Comment by AmanAgnihotri** [comment]
Or you can deal wit the merge conflicts for I'm sending the PR. :laughing:

**Comment by shkesar** [comment]
We need two branches.

**Comment by shkesar** [comment]
Chaos. Chaos. You've merged the PR before I made the last changes.
Github won't revert it.

All new PRs.

**Comment by AmanAgnihotri** [comment]
My OS is currently updating. So couldn't send a PR. I merged it, yes. But still I see no chaos.

Just revert back any formatting change you did after sending me the PR and when I do send you my PR, it'd have the Java code, an updated README and formatted Scala code.

Or deal with merge conflicts manually. Heh.

It's there in my repository right now.

**Comment by shkesar** [comment]
I'll prefer waiting for your changes.

**Comment by AmanAgnihotri** [comment]
Rebooting. Interestingly enough, the major code formatting I wanted in your Scala code was to have a space between the method name and the left parenthesis that marks the position for parameter list.

The braces in new line approach wasn't the type of formatting I was seeking. Since the one you used is the norm for Scala and Java. I still used the braces in new line format in Java one though. Heh.

So just revert your last commit where you did some more code formatting and my PR is incoming.

**Comment by shkesar** [comment]
i was trying to be funny. -_-"
Anyways, this looks way more readable considering the functions with lots of parameters.

**Comment by AmanAgnihotri** [comment]
If it helps, I chuckled when I read your commit message for the "More Code Formatting" change. :smile:

**Comment by shkesar** [comment]
Fine. I don’t expect much from machines. :D

**Comment by AmanAgnihotri** [comment]
I don't know whether to take this as a compliment or reply "I'm hurt" just to fake some sentiments. :laughing:

Embarrassingly enough, the mention of "My OS is currently updating" and "Rebooting" don't help my case either. :laughing:

Maybe two laughs in a single text will.

**Pull request merged**
