### PR TITLE
Aman agnihotri/master

### PR DESCRIPTION
**Pull request by shkesar**

### CODE REVIEW

**Comment by AmanAgnihotri** [comment]
LOL. Although yours shows 3 more commits, I see no file change. Got too overconfident? :laughing:

**Comment by shkesar** [comment]
Final merge ..

Next time, lets both +1 before merging any branch.

**Comment by AmanAgnihotri** [comment]
It'll be a BS merge if I do merge it. Meaningless. And I like the brace style you used earlier, so even if your changes had the newly formatted code with the new line brace style, I wouldn't have merged it. Heh.

Go home, you're drunk.

**Comment by shkesar** [comment]
Woah! Look at this.

screen shot 2015-07-03 at 2 53 27 am

**Comment by shkesar** [comment]
You’re not wrong about booze. :D

**Comment by AmanAgnihotri** [comment]
I see what happened. You basically stumbled when creating the pull request and messed up the "base" and the "head" of it. See for yourself. That is why this PR doesn't show any file change. The "heads" of our repositories as shown in the figure point to the same final commit. Not surprised there as that is how it should be.

**Comment by shkesar** [comment]
My repo is shown 3 commits ahead of yours. :P

That is despite the fact we have same codebase. I didn't wonder that there won't be any head difference before making a PR.

Isn't t this disturbing to you :grey_question:  Add me as a contributor to your repo. I can't tolerate this chaos.

**Comment by AmanAgnihotri** [comment]
Yes its showing. You just messed while creating the PR. I added you as a contributor, but don't mess with my repo in serious ways as well. :P Its about quality and elegance.

**Comment by shkesar** [comment]
Cool. It’ll be a lot easier now to show you what my real intentions are. :P

Muhahahah.

**Pull request closed without merging**
